[tool.poetry]
name = "assistente-pedidos"
version = "0.1.0"
description = ""
authors = ["Alisson <alissonpintor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
<<<<<<< HEAD
scikit-learn = "^1.5.2"
pandas = "^2.2.3"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
scipy = "^1.14.1"
=======
pandas = "^2.2.2"
streamlit = "^1.38.0"
workalendar = "^17.0.0"
>>>>>>> ea6381ce0c5c2cede680a8b96f33e796bdacd956


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
